version: '3.9'

services:
  db:
    image: postgres:15
    container_name: medtik_db
    restart: always
    environment:
      POSTGRES_USER: medtik_user
      POSTGRES_PASSWORD: medtik_pass
      POSTGRES_DB: medtik_db
    ports:
      - "5432:5432"

  backend:
    build: .
    container_name: medtik_backend
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "4000:4000"
    command: >
      sh -c "
        npx prisma generate &&
        npx prisma migrate dev --name init &&
        npx prisma db seed &&
        npm run dev 
      "

  ngrok:
    image: ngrok/ngrok:latest
    command:
      - "http"
      - "http://host.docker.internal:4000"
    environment:
      NGROK_AUTHTOKEN: 33Waj3dZ58cnDFnA0bUif1JTWOG_6dNcDeYHQkxEV5ox5VZvZ
    ports:
      - 4040:4040

