version: "3.9"

services:
  db:
    image: postgres:15
    container_name: medtik_db
    restart: always
    environment:
      POSTGRES_USER: medtik_user
      POSTGRES_PASSWORD: medtik_pass
      POSTGRES_DB: medtik_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: .
    container_name: medtik_backend
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "4000:4000"
    environment:
      NODE_ENV: production
    command: >
      sh -c "
        npx prisma migrate deploy &&
        npm run dev
      "
    volumes:
      - ./uploads:/app/uploads

  prisma-studio:
    build: .
    container_name: medtik_prisma_studio
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "5555:5555"
    command: npx prisma studio --port 5555 --hostname 0.0.0.0

  ngrok:
    image: ngrok/ngrok:latest
    command:
      - "http"
      - "backend:4000"
    environment:
      NGROK_AUTHTOKEN: ${NGROK_AUTHTOKEN}
    ports:
      - "4040:4040"
    depends_on:
      - backend

volumes:
  pgdata:
